# Server Settings
server:
  port: 9000

management:
  port: 9001
  address: 127.0.0.1

# Spring
spring:
  - http:
      encoding.charset: UTF-8
      encoding.enable: true

  - datasource:
      driver: com.mysql.jdbc.Driver
      url: jdbc:mysql://23.83.232.227
      username: root
      password: xiaoguai22

# MyBatis
myBatis:
  configLocation: classpath:mybatis-config.xml
  mapperLocations: classpath:mybatis-mapper/web-user-mapper.xml